apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fga-java-5yyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fga-java-5yyq
    app.kubernetes.io/part-of: my-api-app
  name: fga-java-5yyq
  namespace: rhn-gps-rspazzol-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fga-java-5yyq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fga-java-5yyq
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rhn-gps-rspazzol-tenant-fga-java-5yyq
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
