apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fga-java-5yyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fga-java-5yyq
    app.kubernetes.io/part-of: my-api-app
  name: fga-java-5yyq
  namespace: rhn-gps-rspazzol-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: fga-java-5yyq
status:
  loadBalancer: {}
